version: '3.8'

services:
  boneless-app:
    build: .
    container_name: boneless-web
    ports:
      - "3033:3033"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3033')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.example.description=Página web de Boneless"
      - "com.example.service=web"
